### ISSUE TITLE
No build.sh

### ISSUE THREAD

**Issue by tinchodias** [artoolkit/ar6-wiki#1]
This [page](https://github.com/artoolkit/ar6-wiki/wiki/Setting-up-for-developing-an-ARToolKit-for-Android-app) says:

> Building the Source Code
> 
> Open a terminal or command window:
> cd ARTOOLKIT_ROOT
> cd Source
> ./build.sh android examples

But there is no build.sh in artoolkit6-6.0.2-Android.zip, which I just downloaded from https://www.artoolkit.org/.

**Comment by ThorstenBux** [comment]
The SDK is prebuild. You cannot build it yourself jet. Stay tuned till we release the sources.
You can examine the examples or integrate the lib it into your project, though. 

This tells you how: http://augmentmy.world/integrate-artoolkit6-android-sdk

**Comment by tinchodias** [comment]
Thanks for your fast answer. Then I close the issue.
