### ISSUE TITLE
No Windows support

### ISSUE THREAD

**Issue by rofoto** [artoolkit/ar6-wiki#11]
The toolkit examples do not build properly on Android Studio or Unity on Windows 10 . And the quick start guide says nothing useful to new users. 

-Install the demo .apk and look at source which does not build is not a good way to introduce new users to what looks (at least on its surface) as a good library for cross platform AR development.  

Also it would be helpful to provide a more complete guide on how to build your example. This way a new user can actually begin to understand the system you've built and why it is designed the way it is.

**Comment by philip-lamb** [comment]
Windows is not currently supported. Sorry about that.
